version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - redis-monitor-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: redis-monitor-backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3001
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - redis-monitor-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: redis-monitor-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - redis-monitor-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  redis-monitor-network:
    driver: bridge